name: push-docker-image-to-docker-hub

on:
  push:
    branches:
      - 'main'

jobs:
  PUSH_PHP_IMAGE_TO_DOCKER_HUB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if php files or dockerfile was changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            php:
              - 'php/**'

      - name: Set up QEMU
        if: steps.changes.outputs.php == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: steps.changes.outputs.php == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: steps.changes.outputs.php == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.php == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: php/Dockerfile
          tags: rguasch/php:latest

  SEND_EMAIL:
    needs:
      - PUSH_PHP_IMAGE_TO_DOCKER_HUB
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Docker images pushed to DockerHub
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          body: Build job of ${{github.repository}} completed successfully! PHP image uploaded to DockerHub.
